In [4]:
# ! uv add seaborn

In [7]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic = titanic [ ['survived','pclass','sex','age'] ]
titanic

     survived  pclass     sex   age
0           0       3    male  22.0
1           1       1  female  38.0
2           1       3  female  26.0
3           1       1  female  35.0
4           0       3    male  35.0
..        ...     ...     ...   ...
886         0       2    male  27.0
887         1       1  female  19.0
888         0       3  female   NaN
889         1       1    male  26.0
890         0       3    male  32.0

[891 rows x 4 columns]

In [8]:
titanic.dropna(axis=0,inplace=True)
titanic

/var/folders/ws/g_05yn3j68vchczq_yk1xx4c0000gn/T/ipykernel_1163/2969209930.py:1: Pandas4Warning: The inplace keyword in DataFrame.dropna is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  titanic.dropna(axis=0,inplace=True)

     survived  pclass     sex   age
0           0       3    male  22.0
1           1       1  female  38.0
2           1       3  female  26.0
3           1       1  female  35.0
4           0       3    male  35.0
..        ...     ...     ...   ...
885         0       3  female  39.0
886         0       2    male  27.0
887         1       1  female  19.0
889         1       1    male  26.0
890         0       3    male  32.0

[714 rows x 4 columns]

In [12]:
titanic['sex'] = titanic['sex'].replace(['male','female'],[0,1])

In [13]:
titanic

     survived  pclass sex   age
0           0       3   0  22.0
1           1       1   1  38.0
2           1       3   1  26.0
3           1       1   1  35.0
4           0       3   0  35.0
..        ...     ...  ..   ...
885         0       3   1  39.0
886         0       2   0  27.0
887         1       1   1  19.0
889         1       1   0  26.0
890         0       3   0  32.0

[714 rows x 4 columns]

In [20]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd


y = titanic['survived']
X = titanic.drop('survived',axis = 1)

classifier = KNeighborsClassifier()
classifier.fit(X,y)
classifier.score(X,y)

df_me = pd.DataFrame(np.array([3,0,50]).reshape(1,3),columns=X.columns)



classifier.predict(df_me)

array([0])